project:
  type: website
  output-dir: docs

website:
  title: "R/Medicine 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Register.qmd
        text: Register
      - href: Abstracts.qmd
        text: Abstracts
      - href: Program.qmd
        text: Program
      - href: workshops.qmd
        text: Workshops
      - href: Attend.qmd
        text: Code of Conduct
      - href: Competition.qmd
        text: Competition
      - href: Contact.qmd
        text: Contact us
      - href: Events.qmd
        text: Past Events
      - href: committees.qmd
        text: Committees
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    default-image-extension: svg
editor: visual

execute:
  freeze: auto
