project:
  type: website

website:
  title: "R/Medicine 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Register.qmd
        text: Register
      - href: Attend.qmd
        text: Attend
      - href: Program.qmd
        text: Program
      - href: Contact.qmd
        text: Contact us
      - href: Events.qmd
        text: Past Events

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    default-image-extension: svg
editor: visual
